Repository FOREGG-DEV/FOREGG_Android, pull requests merged in 2024-05, with the labels that each got.

#24 [Feat] 홈 화면 오늘의 일정 구현
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/foregg/data/api/Endpoints.kt
  data/src/main/java/com/foregg/data/api/HomeApi.kt
  data/src/main/java/com/foregg/data/dto/HomeResponse.kt
  data/src/main/java/com/foregg/data/mapper/HomeResponseMapper.kt
  data/src/main/java/com/foregg/data/repository/HomeRepositoryImpl.kt
  domain/src/main/java/com/foregg/domain/model/response/HomeRecordResponseVo.kt
  domain/src/main/java/com/foregg/domain/model/response/HomeResponseVo.kt
  domain/src/main/java/com/foregg/domain/repository/HomeRepository.kt
  domain/src/main/java/com/foregg/domain/usecase/home/GetHomeUseCase.kt
  presentation/src/main/java/com/foregg/presentation/module/ApiModule.kt
  presentation/src/main/java/com/foregg/presentation/module/RepositoryModule.kt
  presentation/src/main/java/com/foregg/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/foregg/presentation/ui/home/HomeEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/home/HomeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/home/HomePageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/home/HomeViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/home/adapter/HomeTodayScheduleAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/home/adapter/HomeTodayScheduleViewHolder.kt
  presentation/src/main/res/drawable/bg_rectangle_filled_personal_radius_4.xml
  presentation/src/main/res/drawable/ic_btn_go_to_challenge.xml
  presentation/src/main/res/drawable/ic_daily_record.xml
  presentation/src/main/res/drawable/ic_empty_challenge.xml
  presentation/src/main/res/drawable/ic_record_treatment.xml
  presentation/src/main/res/drawable/ic_right_arrow_gs_50.xml
  presentation/src/main/res/drawable/ic_right_arrow_main_2.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/item_today_schedule.xml
  presentation/src/main/res/navigation/main_graph.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#46 [Feat] 챌린지 조회, 챌린지 참여, 나의 챌린지 조회, 챌린지 삭제 구현
  data/src/main/java/com/foregg/data/api/ChallengeApi.kt
  data/src/main/java/com/foregg/data/api/Endpoints.kt
  data/src/main/java/com/foregg/data/dto/challenge/ChallengeResponseListItem.kt
  data/src/main/java/com/foregg/data/dto/challenge/MyChallengeResponseListItem.kt
  data/src/main/java/com/foregg/data/mapper/challenge/ChallengeResponseMapper.kt
  data/src/main/java/com/foregg/data/mapper/challenge/MyChallengeResponseMapper.kt
  data/src/main/java/com/foregg/data/repository/ChallengeRepositoryImpl.kt
  domain/src/main/java/com/foregg/domain/model/enums/ChallengeTapType.kt
  domain/src/main/java/com/foregg/domain/model/response/ChallengeCardVo.kt
  domain/src/main/java/com/foregg/domain/model/response/HomeRecordResponseVo.kt
  domain/src/main/java/com/foregg/domain/model/response/HomeResponseVo.kt
  domain/src/main/java/com/foregg/domain/model/response/MyChallengeListItemVo.kt
  domain/src/main/java/com/foregg/domain/repository/ChallengeRepository.kt
  domain/src/main/java/com/foregg/domain/usecase/home/challenge/CompleteChallengeUseCase.kt
  domain/src/main/java/com/foregg/domain/usecase/home/challenge/GetAllChallengeUseCase.kt
  domain/src/main/java/com/foregg/domain/usecase/home/challenge/GetMyChallengeUseCase.kt
  domain/src/main/java/com/foregg/domain/usecase/home/challenge/ParticipateChallengeUseCase.kt
  domain/src/main/java/com/foregg/domain/usecase/home/challenge/QuitChallengeUseCase.kt
  presentation/src/main/java/com/foregg/presentation/module/ApiModule.kt
  presentation/src/main/java/com/foregg/presentation/module/RepositoryModule.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomePageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeTodayScheduleAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeTodayScheduleViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengePageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/adapter/ChallengeListAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/adapter/ChallengeListViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/adapter/MyChallengeListAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/adapter/MyChallengeListViewHolder.kt
  presentation/src/main/res/drawable/bg_circle_filled_gs_30_radius_19.xml
  presentation/src/main/res/drawable/bg_circle_filled_main_radius_19.xml
  presentation/src/main/res/drawable/bg_circle_filled_white_radius_19.xml
  presentation/src/main/res/drawable/bg_circle_filled_white_stroke_pink_radius_19.xml
  presentation/src/main/res/drawable/bg_rectangle_filled_white_stroke_gs_30_radius_4.xml
  presentation/src/main/res/drawable/ic_btn_delete.xml
  presentation/src/main/res/drawable/ic_challenge.xml
  presentation/src/main/res/drawable/ic_challenge_participant.xml
  presentation/src/main/res/layout/fragment_challenge.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/item_challenge.xml
  presentation/src/main/res/layout/item_my_challenge.xml
  presentation/src/main/res/navigation/main_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#53 Feat/31 마이페이지 계정관리(로그아웃, 회원탈퇴), MainActivity 코드 리펙토링
  data/src/main/java/com/foregg/data/api/AuthApi.kt
  data/src/main/java/com/foregg/data/api/Endpoints.kt
  data/src/main/java/com/foregg/data/api/ProfileApi.kt
  data/src/main/java/com/foregg/data/repository/ProfileRepositoryImpl.kt
  domain/src/main/java/com/foregg/domain/model/enums/BottomNavType.kt
  domain/src/main/java/com/foregg/domain/repository/ProfileRepository.kt
  domain/src/main/java/com/foregg/domain/usecase/auth/PostLogoutUseCase.kt
  domain/src/main/java/com/foregg/domain/usecase/auth/PostUnregisterUseCase.kt
  presentation/src/main/java/com/foregg/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/foregg/presentation/ui/MainActivityPageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/MainActivityViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/profile/ProfileFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/profile/account/ProfileAccountEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/profile/account/ProfileAccountFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/profile/account/ProfileAccountViewModel.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/fragment_profile_account.xml
  presentation/src/main/res/navigation/main_graph.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#58 Refactor/57 design gyeong seok
  data/src/main/java/com/foregg/data/api/ProfileApi.kt
  data/src/main/java/com/foregg/data/dto/profile/ProfileDetailResponse.kt
  data/src/main/java/com/foregg/data/mapper/profile/ProfileDetailResponseMapper.kt
  domain/src/main/java/com/foregg/domain/model/response/profile/ProfileDetailResponseVo.kt
  domain/src/main/java/com/foregg/domain/model/vo/CalendarDayVo.kt
  presentation/src/androidTest/java/com/foregg/presentation/ExampleInstrumentedTest.kt
  presentation/src/main/java/com/foregg/presentation/base/BaseViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/adapter/AccountCardViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/createOrEdit/CreateEditScheduleFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/createOrEdit/CreateEditScheduleViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/dialog/CreateScheduleDialog.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/viewHolder/CalendarDayViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeTodayScheduleAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeTodayScheduleViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/profile/edit/EditMyInfoViewModel.kt
  presentation/src/main/res/layout/custom_tab_bar.xml
  presentation/src/main/res/layout/fragment_edit_my_info.xml
  presentation/src/main/res/layout/include_calendar_repeat_day_setting.xml
  presentation/src/main/res/layout/include_item_account_card.xml
  presentation/src/main/res/layout/include_item_day.xml
  presentation/src/main/res/layout/include_layout_calendar_schedule.xml
  presentation/src/main/res/navigation/main_graph.xml
  presentation/src/main/res/values/themes.xml
Labels: bug, design

#62 [Fix] 하루기록 버그 개선
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/adapter/DailyRecordViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createSideEffect/CreateSideEffectViewModel.kt
  presentation/src/main/res/layout/fragment_create_daily_record.xml
  presentation/src/main/res/layout/fragment_create_side_effect.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/item_today_schedule.xml
Labels: bug, design

#64 Feat/59 각종 에러처리, 디자인 개선
  .idea/deploymentTargetDropDown.xml
  data/src/main/java/com/foregg/data/base/BaseRepository.kt
  data/src/main/java/com/foregg/data/base/StatusCode.kt
  data/src/main/java/com/foregg/data/dto/challenge/ChallengeResponseListItem.kt
  data/src/main/java/com/foregg/data/mapper/challenge/ChallengeResponseMapper.kt
  domain/src/main/java/com/foregg/domain/model/vo/CreateEditPageVo.kt
  domain/src/main/java/com/foregg/domain/model/vo/onboarding/OnboardingTutorialVo.kt
  presentation/src/main/java/com/foregg/presentation/base/BaseFragment.kt
  presentation/src/main/java/com/foregg/presentation/base/BaseViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createSideEffect/CreateSideEffectFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/AccountEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/AccountFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/AccountViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/bottomSheet/AccountDatePickBottomSheet.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/createOrEdit/AccountCreateEditEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/createOrEdit/AccountCreateEditFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/createOrEdit/AccountCreateEditViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/CalendarEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/CalendarFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/createOrEdit/CreateEditScheduleEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/createOrEdit/CreateEditScheduleFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/createOrEdit/CreateEditScheduleViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/profile/myMedicineInjection/MedicineInjectionFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/OnboardingEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/OnboardingFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/OnboardingPageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/OnboardingViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/adapter/OnboardingTutorialAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/adapter/OnboardingTutorialViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/chooseGender/ChooseGenderEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/chooseGender/ChooseGenderFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/chooseGender/ChooseGenderViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/female/SignUpFemaleEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/female/SignUpFemaleFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/female/SignUpFemaleViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/male/SignUpMaleEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/male/SignUpMaleFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/male/SignUpMaleViewModel.kt
  presentation/src/main/java/com/foregg/presentation/util/FcmNotification.kt
  presentation/src/main/java/com/foregg/presentation/util/ForeggNotification.kt
  presentation/src/main/res/drawable/onboarding_first.xml
  presentation/src/main/res/layout/fragment_create_daily_record.xml
  presentation/src/main/res/layout/fragment_create_side_effect.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_onboarding.xml
  presentation/src/main/res/layout/include_calendar_repeat_day_setting.xml
  presentation/src/main/res/layout/include_item_tutorial.xml
  presentation/src/main/res/layout/item_today_schedule.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/strings.xml
Labels: bug, enhancement

#65 Feat: 정보 페이지 구현, 디자인 요구사항 반영, 홈 화면 팀 소개 배너 구현, 버그 사항 수정
  data/src/main/java/com/foregg/data/dto/HomeResponse.kt
  domain/src/main/java/com/foregg/domain/model/vo/InfoItemVo.kt
  presentation/src/main/java/com/foregg/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomePageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeChallengeViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeIntroductionAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeIntroductionViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeTodayScheduleViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/adapter/ChallengeListViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/adapter/MyChallengeListViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationPageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationDetailAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationDetailViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/subsidyDetail/SubsidyDetailFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/subsidyDetail/SubsidyDetailPageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/subsidyDetail/SubsidyDetailViewModel.kt
  presentation/src/main/res/drawable/bg_circle_filled_grey.xml
  presentation/src/main/res/drawable/ic_btn_complete_challenge_already.xml
  presentation/src/main/res/drawable/ic_card_inrtoduction.xml
  presentation/src/main/res/drawable/ic_logo.xml
  presentation/src/main/res/layout/fragment_challenge.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_information.xml
  presentation/src/main/res/layout/fragment_subsidy_detail.xml
  presentation/src/main/res/layout/item_challenge.xml
  presentation/src/main/res/layout/item_home_introduction.xml
  presentation/src/main/res/layout/item_home_my_challenge.xml
  presentation/src/main/res/layout/item_info.xml
  presentation/src/main/res/layout/item_info_category.xml
  presentation/src/main/res/layout/item_my_challenge.xml
  presentation/src/main/res/layout/item_today_schedule.xml
  presentation/src/main/res/navigation/main_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: bug, enhancement, design

#68 Feat/67 주사 알람 페이지 수정
  data/src/main/java/com/foregg/data/api/DailyRecordApi.kt
  data/src/main/java/com/foregg/data/api/Endpoints.kt
  data/src/main/java/com/foregg/data/base/BaseRepository.kt
  data/src/main/java/com/foregg/data/base/StatusCode.kt
  data/src/main/java/com/foregg/data/dto/dailyRecord/InjectionInfoResponse.kt
  data/src/main/java/com/foregg/data/mapper/dailyRecord/InjectionInfoResponseMapper.kt
  data/src/main/java/com/foregg/data/repository/DailyRecordRepositoryImpl.kt
  domain/src/main/java/com/foregg/domain/model/request/dailyRecord/InjectionAlarmRequestVo.kt
  domain/src/main/java/com/foregg/domain/model/response/daily/InjectionInfoResponseVo.kt
  domain/src/main/java/com/foregg/domain/model/vo/UserVo.kt
  domain/src/main/java/com/foregg/domain/repository/DailyRecordRepository.kt
  domain/src/main/java/com/foregg/domain/usecase/dailyRecord/GetInjectionInfoUseCase.kt
  domain/src/main/java/com/foregg/domain/usecase/dailyRecord/PostShareInjectionUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/foregg/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/injection/InjectionEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/injection/InjectionFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/injection/InjectionPageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/injection/InjectionViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/OnboardingFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/OnboardingViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/female/SignUpFemaleViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/signUp/male/SignUpMaleViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/splash/SplashFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/splash/SplashViewModel.kt
  presentation/src/main/java/com/foregg/presentation/util/AlarmReceiver.kt
  presentation/src/main/java/com/foregg/presentation/util/AlarmService.kt
  presentation/src/main/java/com/foregg/presentation/util/FcmNotification.kt
  presentation/src/main/java/com/foregg/presentation/util/ForeggNotification.kt
  presentation/src/main/res/layout/fragment_injection.xml
  presentation/src/main/res/navigation/main_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: bug, enhancement
