Repository FOREGG-DEV/FOREGG_Android, pull requests merged in 2024-06, with the labels that each got.

#69 [Feat] 남편 홈 화면, 남편 하루 기록 구현
  .idea/appInsightsSettings.xml
  data/src/main/java/com/foregg/data/api/DailyRecordApi.kt
  data/src/main/java/com/foregg/data/api/Endpoints.kt
  data/src/main/java/com/foregg/data/dto/HomeResponse.kt
  data/src/main/java/com/foregg/data/mapper/HomeResponseMapper.kt
  data/src/main/java/com/foregg/data/repository/DailyRecordRepositoryImpl.kt
  domain/src/main/java/com/foregg/domain/model/request/dailyRecord/EmotionVo.kt
  domain/src/main/java/com/foregg/domain/model/request/dailyRecord/PutEmotionVo.kt
  domain/src/main/java/com/foregg/domain/model/response/HomeResponseVo.kt
  domain/src/main/java/com/foregg/domain/repository/DailyRecordRepository.kt
  domain/src/main/java/com/foregg/domain/usecase/dailyRecord/PutEmotionUseCase.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordPageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/adapter/DailyRecordAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/adapter/DailyRecordViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomePageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeTodayScheduleViewHolder.kt
  presentation/src/main/res/drawable/ic_empty_challenge.xml
  presentation/src/main/res/layout/fragment_challenge.xml
  presentation/src/main/res/layout/fragment_create_side_effect.xml
  presentation/src/main/res/layout/fragment_daily_record.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/item_challenge.xml
  presentation/src/main/res/layout/item_daily_record.xml
  presentation/src/main/res/layout/item_today_schedule.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#72 Fix/70 fix design
  .idea/deploymentTargetDropDown.xml
  domain/src/main/java/com/foregg/domain/model/vo/CreateScheduleTimeVo.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/account/AccountViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/createOrEdit/CreateEditScheduleFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/createOrEdit/CreateEditScheduleViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/calendar/createOrEdit/viewHolder/SettingTimeViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/injection/InjectionPageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/injection/InjectionViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/sign/onBoarding/OnboardingViewModel.kt
  presentation/src/main/res/drawable/ic_clock.xml
  presentation/src/main/res/drawable/onboarding_fourth.xml
  presentation/src/main/res/drawable/onboarding_second.xml
  presentation/src/main/res/drawable/onboarding_third.xml
  presentation/src/main/res/layout/fragment_injection.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/include_item_day.xml
  presentation/src/main/res/layout/include_item_setting_schedule_time.xml
  presentation/src/main/res/layout/include_item_tutorial.xml
  presentation/src/main/res/layout/include_layout_calendar_medical_record.xml
  presentation/src/main/res/layout/include_layout_calendar_schedule.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: bug, enhancement, design

#73 [Refactor] 디자인 수정사항 반영
  data/src/main/java/com/foregg/data/base/StatusCode.kt
  presentation/src/main/java/com/foregg/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomePageState.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/HomeViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeTodayScheduleAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/adapter/HomeTodayScheduleViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/home/challenge/ChallengeFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationViewModel.kt
  presentation/src/main/res/drawable/ic_btn_add_filled_main.xml
  presentation/src/main/res/drawable/ic_btn_go_to_challenge.xml
  presentation/src/main/res/drawable/ic_empty_challenge_my.xml
  presentation/src/main/res/layout/fragment_challenge.xml
  presentation/src/main/res/layout/fragment_daily_record.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_information.xml
  presentation/src/main/res/layout/item_today_schedule.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement, design

#76 ✨feat - coil을 이용한 svg load
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/foregg/data/dto/dailyRecord/InjectionInfoResponse.kt
  data/src/main/java/com/foregg/data/mapper/dailyRecord/InjectionInfoResponseMapper.kt
  domain/src/main/java/com/foregg/domain/model/response/daily/InjectionInfoResponseVo.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/foregg/presentation/ui/main/injection/InjectionFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/injection/InjectionViewModel.kt
  presentation/src/main/java/com/foregg/presentation/util/SvgImageUtil.kt
  presentation/src/main/res/drawable/img_injection_loading.xml
  presentation/src/main/res/layout/fragment_injection.xml
  presentation/src/main/res/layout/include_layout_calendar_schedule.xml
Labels: enhancement

#79 [Feat] 하루기록 수정, 삭제 구현
  data/src/main/java/com/foregg/data/api/DailyRecordApi.kt
  data/src/main/java/com/foregg/data/api/Endpoints.kt
  data/src/main/java/com/foregg/data/repository/DailyRecordRepositoryImpl.kt
  domain/src/main/java/com/foregg/domain/model/request/dailyRecord/EditDailyRecordRequestVo.kt
  domain/src/main/java/com/foregg/domain/model/vo/InfoItemVo.kt
  domain/src/main/java/com/foregg/domain/repository/DailyRecordRepository.kt
  domain/src/main/java/com/foregg/domain/usecase/dailyRecord/DeleteDailyRecordUseCase.kt
  domain/src/main/java/com/foregg/domain/usecase/dailyRecord/EditDailyRecordUseCase.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/DailyRecordViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/adapter/DailyRecordAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/adapter/DailyRecordViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/bottomSheet/DailyRecordEditDeleteBottomSheet.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/dailyRecord/createDailyRecord/CreateDailyRecordViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationDetailAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationDetailViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/subsidyDetail/SubsidyDetailFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/subsidyDetail/SubsidyDetailViewModel.kt
  presentation/src/main/res/drawable/bg_rectangle_filled_background_radius_15.xml
  presentation/src/main/res/drawable/ic_clap.xml
  presentation/src/main/res/drawable/ic_finger_heart.xml
  presentation/src/main/res/layout/bottom_sheet_dialog_daily_record_edit_delete.xml
  presentation/src/main/res/layout/item_daily_record.xml
  presentation/src/main/res/layout/item_info.xml
  presentation/src/main/res/layout/item_info_category.xml
  presentation/src/main/res/layout/item_info_category_detail.xml
  presentation/src/main/res/navigation/main_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement, design

#77 Feat: 정보 페이지 디자인 수정
  domain/src/main/java/com/foregg/domain/model/vo/InfoItemVo.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationEvent.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/InformationViewModel.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationDetailAdapter.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationDetailViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/adapter/InformationViewHolder.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/subsidyDetail/SubsidyDetailFragment.kt
  presentation/src/main/java/com/foregg/presentation/ui/main/information/subsidyDetail/SubsidyDetailViewModel.kt
  presentation/src/main/res/layout/item_info.xml
  presentation/src/main/res/layout/item_info_category.xml
  presentation/src/main/res/layout/item_info_category_detail.xml
  presentation/src/main/res/navigation/main_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement, design
